#!/usr/bin/env python3
"""
deploy_kobo_forms.py
────────────────────
Uploads, deploys, and retrieves Enketo single-submission URLs for all
sub-form XLSForms generated by generate_kobo_and_pages.py.

After running this script, SUBFORM_URL_* entries are written back to
config.env automatically. Then re-run generate_kobo_and_pages.py to
regenerate master.html with the live Enketo URLs baked in.

Usage:
    python3 deploy_kobo_forms.py            # deploy all groups
    python3 deploy_kobo_forms.py --list     # list existing assets only
    python3 deploy_kobo_forms.py --redeploy # redeploy (update) existing assets

Requirements:
    pip install requests
"""

import os, sys, time, re, json, argparse, pathlib, datetime
import requests

# ═══════════════════════════════════════════════════════════════
# Load config.env (same loader as generate_kobo_and_pages.py)
# ═══════════════════════════════════════════════════════════════
def load_config(path="config.env"):
    """Returns (cfg_dict, resolved_path)."""
    import pathlib
    cwd_path   = pathlib.Path.cwd() / path
    script_dir = pathlib.Path(__file__).parent / path
    if cwd_path.exists():
        config_path = cwd_path
    elif script_dir.exists():
        config_path = script_dir
    else:
        return {}, None
    cfg = {}
    with open(config_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            cfg[k.strip()] = v.strip()
    return cfg, config_path


cfg, CONFIG_PATH = load_config()
def _get(k, default=""):
    return cfg.get(k, default)

KOBO_SERVER   = _get("KOBO_SERVER",  "https://eu.kobotoolbox.org")  # change to kf.kobotoolbox.org for global
KOBO_TOKEN    = _get("KOBO_TOKEN",   "")
TOPIC_CODE    = _get("TOPIC_CODE",   "YOUR_PROGRAM_CODE")
OUTPUT_KOBO   = _get("OUTPUT_KOBO",  f"delphi_w1_{TOPIC_CODE}_kobo.xlsx")
KOBO_DIR      = _get("KOBO_DIR",     "kobo_gen")

# Derive subform slugs from existing SUBFORM_URL_* keys or XLS files
def get_slugs():
    """Find all generated XLS files matching the output pattern."""
    base = re.sub(r"\.xlsx$", "", os.path.basename(OUTPUT_KOBO), flags=re.IGNORECASE)
    slugs = []
    if not os.path.isdir(KOBO_DIR):
        return slugs
    for f in sorted(os.listdir(KOBO_DIR)):
        if f.startswith(base + "_") and f.endswith(".xlsx"):
            slug = f[len(base) + 1 : -len(".xlsx")]
            slugs.append(slug)
    return slugs

# ═══════════════════════════════════════════════════════════════
# KoboToolbox API helpers
# ═══════════════════════════════════════════════════════════════
def headers():
    if not KOBO_TOKEN:
        print("❌  KOBO_TOKEN not set in config.env")
        print("    Get your token from: Account Settings → API Token")
        sys.exit(1)
    return {
        "Authorization": f"Token {KOBO_TOKEN}",
        "Accept": "application/json",
    }

def api(method, path, **kwargs):
    url = f"{KOBO_SERVER.rstrip('/')}/api/v2/{path.lstrip('/')}"
    r = getattr(requests, method)(url, headers=headers(), **kwargs)
    if not r.ok:
        print(f"  API error {r.status_code}: {r.text[:300]}")
    return r

def upload_xlsform(xlsx_path, form_name):
    """Upload XLSForm and return asset uid."""
    print(f"  Uploading {xlsx_path}…")
    with open(xlsx_path, "rb") as f:
        r = requests.post(
            f"{KOBO_SERVER.rstrip('/')}/api/v2/imports/",
            headers=headers(),
            files={"file": (os.path.basename(xlsx_path), f,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")},
            data={"name": form_name, "library": "false"},
        )
    if not r.ok:
        print(f"  ❌ Upload failed {r.status_code}: {r.text[:300]}")
        return None

    import_url = r.json().get("url")
    if not import_url:
        print("  ❌ No import URL in response")
        return None

    # Poll until import completes
    for attempt in range(20):
        time.sleep(2)
        poll = requests.get(import_url, headers=headers())
        data = poll.json()
        status = data.get("status", "")
        if status == "complete":
            uid = data.get("messages", {}).get("created", [{}])[0].get("uid")
            if uid:
                print(f"  ✓ Imported — asset uid: {uid}")
                return uid
            # Sometimes uid is nested differently
            created = data.get("messages", {}).get("updated", [])
            if created:
                uid = created[0].get("uid")
                if uid:
                    print(f"  ✓ Updated — asset uid: {uid}")
                    return uid
        elif status == "error":
            print(f"  ❌ Import error: {data.get('messages', '')}")
            return None
        print(f"    … waiting (attempt {attempt+1}, status={status})")

    print("  ❌ Import timed out")
    return None

def deploy_asset(uid):
    """Deploy (or redeploy) an asset. Returns True on success."""
    print(f"  Deploying asset {uid}…")

    # Fetch the asset to find the latest (undeployed) version_id.
    # After a content PATCH, Kobo creates a new draft version. We must
    # deploy that draft explicitly. The top-level "version_id" field is
    # the LATEST version (deployed or not); "deployed_version_id" is what
    # is currently live. We want the latest, not the deployed one.
    version_id = None
    r_asset = api("get", f"assets/{uid}/")
    if r_asset.ok:
        data = r_asset.json()
        # "version_id" = newest version; "deployed_version_id" = currently live
        latest   = data.get("version_id")
        deployed = data.get("deployed_version_id")
        print(f"  Latest version:   {latest}")
        print(f"  Deployed version: {deployed}")
        if latest and latest != deployed:
            print(f"  ℹ️  Unpublished changes detected — will deploy latest")
        version_id = latest  # always target the newest version

    deploy_data = {"active": "true"}
    if version_id:
        deploy_data["version_id"] = version_id

    r = api("post", f"assets/{uid}/deployment/", data=deploy_data)
    if r.ok:
        print(f"  ✓ Deployed")
        return True
    # 405 = already deployed (use PATCH), 409 = conflict (also use PATCH)
    if r.status_code in (405, 409):
        r2 = api("patch", f"assets/{uid}/deployment/", data=deploy_data)
        if r2.ok:
            resp = r2.json()
            live_ver = resp.get("version_id") or resp.get("deployed_version_id") or "?"
            print(f"  ✓ Redeployed (live version now: {live_ver})")
            if version_id and live_ver != version_id:
                print(f"  ⚠️  WARNING: expected {version_id}, got {live_ver}")
                print(f"      Kobo did not promote the new draft.")
            return True
    print(f"  ❌ Deploy failed")
    return False

def set_public_permissions(uid):
    """
    Grant AnonymousUser 'view_asset' and 'add_submissions' on the asset.
    This is equivalent to setting "Allow submissions from anyone with the link"
    in the KoboToolbox UI — without it the single-submission Enketo URL will
    prompt for a Kobo login.
    """
    base = KOBO_SERVER.rstrip('/')
    for permission in ("view_asset", "add_submissions"):
        r = api("post", f"assets/{uid}/permission-assignments/",
                json={
                    "user": f"{base}/api/v2/users/AnonymousUser/",
                    "permission": f"{base}/api/v2/permissions/{permission}/",
                })
        if r.ok or r.status_code == 400:
            # 400 often means already assigned — treat as success
            print(f"  ✓ AnonymousUser {permission}")
        else:
            print(f"  ⚠️  Could not set {permission}: {r.status_code} {r.text[:120]}")

def flush_enketo_cache(uid):
    """
    Ask KoboToolbox to flush Enketo's server-side form cache for this asset.
    Without this, Enketo may serve the old compiled form even after a successful
    redeploy — the timestamp updates but the form content doesn't change.
    KoboToolbox itself calls this internally when you redeploy via the UI.
    """
    r = api("patch", f"assets/{uid}/deployment/",
            data={"active": "true", "reset": "true"})
    if r.ok:
        print(f"  ✓ Enketo cache flushed")
    else:
        print(f"  ℹ️  Cache flush returned {r.status_code} (non-fatal)")

def get_enketo_single_url(uid):
    """
    Retrieve the single-submission Enketo URL for a deployed asset.
    KoboToolbox stores this in deployment__links.offline_url or
    deployment__links.single_url depending on server version.
    """
    r = api("get", f"assets/{uid}/")
    if not r.ok:
        return None
    data = r.json()
    links = data.get("deployment__links", {})
    # Prefer single_url, fall back to offline_url then url
    for key in ("single_url", "single_once_url", "offline_url", "url"):
        url = links.get(key)
        if url:
            print(f"  ✓ Enketo URL ({key}): {url}")
            return url
    print(f"  ⚠️  No Enketo URL found. deployment__links: {links}")
    return None


def find_existing_asset(slug):
    """
    Find the existing asset UID for a given slug.
    Priority:
    1. SUBFORM_ASSET_<slug> already in config.env  (most reliable)
    2. Search account assets by name, then verify id_string via individual fetch
    """
    # 1. Check config first
    config_uid = _get(f"SUBFORM_ASSET_{slug}", "").strip()
    if config_uid:
        print(f"  Found existing asset in config: {config_uid}")
        return config_uid

    # 2. Search by name — the list endpoint doesn't return content.settings,
    #    so fetch each candidate individually to check id_string
    form_id   = f"delphi_w1_{TOPIC_CODE}_{slug}"
    form_name = f"W1 Delphi | {TOPIC_CODE.capitalize()} | {slug}"

    # Try name search first (faster)
    r = api("get", "assets/", params={"q": form_name, "format": "json", "limit": 50})
    candidates = r.json().get("results", []) if r.ok else []

    # Also try id_string search
    r2 = api("get", "assets/", params={"q": form_id, "format": "json", "limit": 50})
    if r2.ok:
        for a in r2.json().get("results", []):
            if a not in candidates:
                candidates.append(a)

    for asset in candidates:
        uid = asset.get("uid")
        if not uid:
            continue
        # Fetch full asset to get content.settings.id_string
        detail = api("get", f"assets/{uid}/", params={"format": "json"})
        if not detail.ok:
            continue
        data     = detail.json()
        settings = data.get("content", {}).get("settings", {})
        if isinstance(settings, list):
            settings = settings[0] if settings else {}
        if settings.get("id_string") == form_id:
            print(f"  Found existing asset by id_string: {uid}")
            return uid
        # Also match on name as fallback
        if data.get("name", "") == form_name:
            print(f"  Found existing asset by name: {uid}")
            return uid

    return None

# ═══════════════════════════════════════════════════════════════
# Write SUBFORM_URL_* back to config.env
# ═══════════════════════════════════════════════════════════════
def update_config_env(slug, url, config_path=None, key_prefix="SUBFORM_URL_"):
    if config_path is None:
        config_path = str(CONFIG_PATH) if CONFIG_PATH else str(pathlib.Path(__file__).parent / "config.env")
    key = f"{key_prefix}{slug}"
    lines = []
    found = False
    if os.path.exists(config_path):
        with open(config_path, encoding="utf-8") as f:
            lines = f.readlines()
    new_lines = []
    for line in lines:
        if line.strip().startswith(key):
            new_lines.append(f"{key} = {url}\n")
            found = True
        else:
            new_lines.append(line)
    if not found:
        # Append after last SUBFORM_URL_ line, or at end
        insert_at = len(new_lines)
        for i, line in enumerate(new_lines):
            if line.strip().startswith("SUBFORM_URL_"):
                insert_at = i + 1
        new_lines.insert(insert_at, f"{key} = {url}\n")
    with open(config_path, "w", encoding="utf-8") as f:
        f.writelines(new_lines)
    print(f"  ✓ config.env updated: {key}")

# ═══════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════
def main():
    parser = argparse.ArgumentParser(description="Deploy Kobo sub-forms")
    parser.add_argument("--list",     action="store_true", help="List existing assets only")
    parser.add_argument("--redeploy", action="store_true", help="Redeploy existing assets (update form content)")
    args = parser.parse_args()

    slugs = get_slugs()
    if not slugs:
        print("❌  No XLSForm files found matching pattern:")
        print(f"    {KOBO_DIR}/{re.sub(r'.xlsx$', '', os.path.basename(OUTPUT_KOBO))}_<slug>.xlsx")
        print("    Run generate_kobo_and_pages.py first.")
        sys.exit(1)

    print(f"Found {len(slugs)} sub-form(s): {', '.join(slugs)}")
    print(f"Kobo XLS dir: {KOBO_DIR}")
    print(f"KoboToolbox server: {KOBO_SERVER}\n")

    if args.list:
        print("Existing assets:")
        r = api("get", "assets/", params={"format": "json", "limit": 100})
        if r.ok:
            for asset in r.json().get("results", []):
                print(f"  {asset['uid']}  {asset['name']}")
        return

    results = {}  # slug → enketo_url

    for slug in slugs:
        base = re.sub(r"\.xlsx$", "", os.path.basename(OUTPUT_KOBO), flags=re.IGNORECASE)
        xlsx_path = os.path.join(KOBO_DIR, f"{base}_{slug}.xlsx")
        form_name = f"W1 Delphi | {TOPIC_CODE.capitalize()} | {slug}"

        print(f"\n{'─'*55}")
        print(f"Group: {slug}")
        print(f"{'─'*55}")

        uid = None

        if args.redeploy:
            # Try to find and update existing asset
            uid = find_existing_asset(slug)
            if uid:
                # Replace form content via /imports/ (same path as the UI uses)
                if not os.path.exists(xlsx_path):
                    print(f"  ❌ XLS file not found: {xlsx_path}")
                    print(f"      Run generate_kobo_and_pages.py first to create it.")
                    continue
                mtime = datetime.datetime.fromtimestamp(os.path.getmtime(xlsx_path))
                print(f"  Uploading: {xlsx_path}")
                print(f"  File date: {mtime.strftime('%Y-%m-%d %H:%M:%S')}")
                with open(xlsx_path, "rb") as f:
                    r = requests.post(
                        f"{KOBO_SERVER.rstrip('/')}/api/v2/imports/",
                        headers=headers(),
                        files={"file": (os.path.basename(xlsx_path), f,
                               "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")},
                        data={"destination": f"{KOBO_SERVER.rstrip('/')}/api/v2/assets/{uid}/",
                              "library": "false"},
                    )
                if not r.ok:
                    print(f"  ❌ Import failed ({r.status_code}): {r.text[:300]}")
                    continue
                # Poll until complete
                import_url = r.json().get("url")
                updated = False
                if import_url:
                    for attempt in range(20):
                        time.sleep(2)
                        poll = requests.get(import_url, headers=headers())
                        data = poll.json()
                        status = data.get("status", "")
                        if status == "complete":
                            updated = True
                            break
                        elif status == "error":
                            print(f"  ❌ Import error: {data.get('messages', '')}")
                            break
                        print(f"    … waiting (attempt {attempt+1}, status={status})")
                if updated:
                    print(f"  ✓ Form content updated via imports/")
                else:
                    print(f"  ⚠️  Import did not confirm completion — proceeding anyway")
            else:
                print(f"  ⚠️  Could not find existing asset for slug '{slug}'.")
                print(f"      Add SUBFORM_ASSET_{slug} = <uid> to config.env to target it explicitly.")
                print(f"      Skipping to avoid creating a duplicate. Use --list to find the UID.")
                continue
        else:
            uid = upload_xlsform(xlsx_path, form_name)
            if not uid:
                print(f"  ❌ Skipping {slug}")
                continue
            if not uid:
                print(f"  ❌ Skipping {slug}")
                continue

        if not deploy_asset(uid):
            print(f"  ❌ Could not deploy {slug}")
            continue

        # Flush Enketo's server-side cache so the new form version is served
        flush_enketo_cache(uid)

        set_public_permissions(uid)

        # Small pause to let Enketo register
        time.sleep(5)

        enketo_url = get_enketo_single_url(uid)
        if enketo_url:
            results[slug] = enketo_url
            update_config_env(slug, enketo_url)
        else:
            print(f"  ⚠️  Could not retrieve Enketo URL for {slug}")
            print(f"      Check manually at: {KOBO_SERVER}/forms/{uid}/")

        # Always store the asset UID so aggregate_results.py can fetch by UID
        update_config_env(slug, uid, key_prefix="SUBFORM_ASSET_")

    print(f"\n{'═'*55}")
    print(f"Done. {len(results)}/{len(slugs)} forms deployed successfully.")

    if results:
        # Auto-regenerate HTML pages so master.html picks up new Enketo URLs
        generate_script = os.path.join(os.path.dirname(__file__),
                                       "generate_kobo_and_pages.py")
        if os.path.exists(generate_script):
            print(f"\nRegenerating pages with updated Enketo URLs…")
            import subprocess
            r = subprocess.run([sys.executable, generate_script],
                               capture_output=True, text=True)
            if r.returncode == 0:
                # Print just the summary line
                for line in r.stdout.splitlines():
                    if line.strip():
                        print(f"  {line}")
            else:
                print(f"  ⚠️  Page regeneration failed:")
                print(r.stderr[-500:] if r.stderr else r.stdout[-500:])
                print(f"  Run manually: python3 generate_kobo_and_pages.py")
        else:
            print(f"\n  ⚠️  generate_kobo_and_pages.py not found — run it manually")
            print(f"      to regenerate master.html with the new Enketo URLs.")

    print(f"{'═'*55}")

if __name__ == "__main__":
    main()
