#!/usr/bin/env python3
"""
make_secrets_toml.py
====================
Combines config.env and deployed_forms.env into a secrets.toml ready to
paste into the Streamlit Cloud app settings (Settings → Secrets).

Keys written:
  From config.env      — TOPIC_CODE, KOBO_SERVER, KOBO_TOKEN
  From deployed_forms.env — SUBFORM_ASSET_* (all entries)

Usage:
    python make_secrets_toml.py               # writes secrets.toml
    python make_secrets_toml.py --print       # prints to stdout only
    python make_secrets_toml.py --out path/to/secrets.toml
"""

import sys
import pathlib

# ── Keys to pull from config.env ──────────────────────────────
CONFIG_KEYS = ["TOPIC_CODE", "KOBO_SERVER", "KOBO_TOKEN"]


def load_env(path):
    cfg = {}
    p = pathlib.Path(path)
    if not p.exists():
        return cfg
    with open(p, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            cfg[k.strip()] = v.strip()
    return cfg


def toml_str(val):
    """Escape backslashes and quotes, wrap in double quotes."""
    val = val.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{val}"'


def build_toml(config_path="config.env", deployed_path="deployed_forms.env"):
    cfg      = load_env(config_path)
    deployed = load_env(deployed_path)

    lines = ["# Streamlit Cloud secrets — generated by make_secrets_toml.py",
             "# Paste into: App settings → Secrets", ""]

    # ── Section 1: topic / credentials ────────────────────────
    lines.append("# ── Topic & Kobo credentials ─────────────────────────────")
    missing = []
    for key in CONFIG_KEYS:
        val = cfg.get(key, "")
        if val:
            lines.append(f"{key} = {toml_str(val)}")
        else:
            missing.append(key)
    if missing:
        lines.append("")
        for key in missing:
            lines.append(f"# WARNING: {key} not found in config.env")

    # ── Section 2: SUBFORM_ASSET_* ────────────────────────────
    assets = {k: v for k, v in deployed.items()
              if k.upper().startswith("SUBFORM_ASSET_") and v.strip()}
    if assets:
        lines.append("")
        lines.append("# ── Kobo asset UIDs (from deployed_forms.env) ────────────")
        for key, val in sorted(assets.items()):
            lines.append(f"{key} = {toml_str(val)}")
    else:
        lines.append("")
        lines.append("# WARNING: no SUBFORM_ASSET_* entries found in deployed_forms.env")

    return "\n".join(lines) + "\n"


def main():
    print_only = "--print" in sys.argv
    out_path   = "secrets.toml"
    for i, arg in enumerate(sys.argv[1:], 1):
        if arg == "--out" and i < len(sys.argv) - 1:
            out_path = sys.argv[i + 1]

    # Resolve paths relative to cwd first, then script dir
    def resolve(name):
        cwd = pathlib.Path.cwd() / name
        script = pathlib.Path(__file__).parent / name
        return str(cwd) if cwd.exists() else str(script)

    toml = build_toml(resolve("config.env"), resolve("deployed_forms.env"))

    if print_only:
        print(toml)
        return

    out = pathlib.Path(out_path)
    out.write_text(toml, encoding="utf-8")
    print(f"Written: {out.resolve()}")
    print()
    print("── Contents ────────────────────────────────────────────")
    print(toml)
    print("────────────────────────────────────────────────────────")
    print("Copy the block above into Streamlit Cloud → App settings → Secrets.")


if __name__ == "__main__":
    main()
