#!/usr/bin/env python3
"""
run_tests.py
============
Lightweight regression/integration test runner for this repository.

Commands
--------
List scenarios and available variants:
  python code/run_tests.py list

Run one scenario (base regression run):
  python code/run_tests.py run --scenario hiv_teams

Run one scenario integration variant (dictionary -> kobo/pages):
  python code/run_tests.py run --scenario hiv_teams --variant integration

Run all scenarios (base variant):
  python code/run_tests.py run-all

Run all scenarios and all variants:
  python code/run_tests.py run-all --all-variants

Clean generated outputs:
  python code/run_tests.py clean
  python code/run_tests.py clean --scenario hiv_teams

Variant model
-------------
- base: uses tests/<scenario>/config.env directly.
- integration: runs generate_dictionaries.py first using fixture catalog,
  then runs generate_kobo_and_pages.py with INPUT_FILE overridden to the
  dictionary generated into out/.
- custom: any config file under tests/<scenario>/variants/*.env can be run via
  --variant <name>, where <name> is the filename stem.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional

ROOT = Path(__file__).resolve().parents[1]
TESTS_DIR = ROOT / "tests"
CODE_DIR = ROOT / "code"
# Use the same Python interpreter that launched this runner so subprocesses
# keep the exact same environment/dependencies.
PYTHON = sys.executable


@dataclass
class Scenario:
    name: str
    path: Path
    config: Path
    fixture: Path
    expected: Path
    out: Path


def parse_env_file(path: Path) -> Dict[str, str]:
    # Minimal .env parser intentionally aligned with project config style:
    # KEY = VALUE, comments/blank lines ignored.
    cfg: Dict[str, str] = {}
    if not path.exists():
        return cfg
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        cfg[key.strip()] = value.strip()
    return cfg


def discover_scenarios() -> List[Scenario]:
    # A scenario is any direct child folder of tests/ that has config.env.
    # This keeps onboarding simple: create folder + config and it is discovered.
    scenarios: List[Scenario] = []
    if not TESTS_DIR.exists():
        return scenarios
    for item in sorted(TESTS_DIR.iterdir()):
        if not item.is_dir() or item.name.startswith("."):
            continue
        config = item / "config.env"
        if not config.exists():
            continue
        scenarios.append(
            Scenario(
                name=item.name,
                path=item,
                config=config,
                fixture=item / "fixture",
                expected=item / "expected",
                out=item / "out",
            )
        )
    return scenarios


def list_variants(scenario: Scenario) -> List[str]:
    # Built-in variants always available for every scenario.
    names = ["base", "integration"]
    variants_dir = scenario.path / "variants"
    if variants_dir.exists():
        for envf in sorted(variants_dir.glob("*.env")):
            names.append(envf.stem)
    return names


def run_cmd(cmd: List[str], cwd: Optional[Path] = None) -> None:
    print("$", " ".join(cmd))
    subprocess.run(cmd, cwd=str(cwd or ROOT), check=True)


def pick_catalog_file(scenario: Scenario) -> Optional[Path]:
    # Integration mode needs a source catalog workbook. Convention:
    # first .xlsx in fixture/ that is NOT already a generated dictionary.
    if not scenario.fixture.exists():
        return None
    candidates = sorted(
        p for p in scenario.fixture.glob("*.xlsx") if not p.name.lower().startswith("dicionario_")
    )
    return candidates[0] if candidates else None


def make_temp_config(base_config: Path, overrides: Dict[str, str]) -> Path:
    # Integration mode needs to reuse scenario config while overriding INPUT_FILE
    # to point at the dictionary generated into out/. We write a temp config
    # to avoid mutating checked-in scenario files.
    cfg = parse_env_file(base_config)
    cfg.update(overrides)
    with tempfile.NamedTemporaryFile("w", suffix=".env", delete=False, encoding="utf-8") as tmp:
        tmp.write("# generated by run_tests.py\n")
        for key, value in cfg.items():
            tmp.write(f"{key} = {value}\n")
        return Path(tmp.name)


def run_base_variant(scenario: Scenario, config_path: Path) -> None:
    # Base regression path: execute kobo/pages generator exactly as configured.
    run_cmd([
        PYTHON,
        str(CODE_DIR / "generate_kobo_and_pages.py"),
        "--config",
        str(config_path),
    ])


def run_integration_variant(scenario: Scenario, config_path: Path) -> None:
    # Integration path:
    #   1) catalog fixture -> dictionary (out/)
    #   2) dictionary (out/) -> kobo/pages
    cfg = parse_env_file(config_path)
    program = (cfg.get("TOPIC_CODE", scenario.name) or scenario.name).strip().lower()
    catalog = pick_catalog_file(scenario)
    if not catalog:
        raise RuntimeError(f"No fixture catalog .xlsx found under {scenario.fixture}")

    scenario.out.mkdir(parents=True, exist_ok=True)

    run_cmd([
        PYTHON,
        str(CODE_DIR / "generate_dictionaries.py"),
        "--program", program,
        "--catalog", str(catalog),
        "--output-dir", str(scenario.out),
        "--config", str(config_path),
    ])

    generated_dict = scenario.out / f"dicionario_delphi_w1_{program}.xlsx"
    if not generated_dict.exists():
        raise RuntimeError(f"Expected generated dictionary not found: {generated_dict}")

    temp_cfg = make_temp_config(config_path, {"INPUT_FILE": str(generated_dict)})
    try:
        run_base_variant(scenario, temp_cfg)
    finally:
        try:
            temp_cfg.unlink(missing_ok=True)
        except Exception:
            pass


def resolve_variant_config(scenario: Scenario, variant: str) -> Path:
    # Custom variants are just alternate .env files under variants/.
    if variant in ("base", "integration"):
        return scenario.config
    variant_file = scenario.path / "variants" / f"{variant}.env"
    if not variant_file.exists():
        raise RuntimeError(f"Variant config not found: {variant_file}")
    return variant_file


def run_scenario(scenario: Scenario, variant: str) -> None:
    config = resolve_variant_config(scenario, variant)
    print(f"\n=== Scenario: {scenario.name} | Variant: {variant} ===")
    if variant == "integration":
        run_integration_variant(scenario, config)
    else:
        run_base_variant(scenario, config)
    print(f"PASS  {scenario.name} [{variant}]")


def clean_scenario_outputs(scenario: Scenario) -> None:
    # Remove generated artifacts but keep hidden files and checked-in fixtures.
    out = scenario.out
    if not out.exists():
        return
    for child in out.iterdir():
        if child.name.startswith("."):
            continue
        if child.is_dir():
            shutil.rmtree(child)
        else:
            child.unlink()
    print(f"cleaned: {out}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Regression/integration test runner")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("list", help="List discovered scenarios and variants")

    p_run = sub.add_parser("run", help="Run one scenario")
    p_run.add_argument("--scenario", required=True, help="Scenario folder under tests/")
    p_run.add_argument("--variant", default="base", help="base|integration|<custom variant name>")

    p_all = sub.add_parser("run-all", help="Run all scenarios")
    p_all.add_argument("--all-variants", action="store_true", help="Run all variants for each scenario")

    p_clean = sub.add_parser("clean", help="Clean generated outputs under tests/*/out")
    p_clean.add_argument("--scenario", help="Optional one scenario to clean")

    args = parser.parse_args()
    scenarios = discover_scenarios()
    by_name = {s.name: s for s in scenarios}

    if args.command == "list":
        if not scenarios:
            print("No scenarios found.")
            return 0
        for s in scenarios:
            print(f"- {s.name}")
            print(f"  config:   {s.config.relative_to(ROOT)}")
            print(f"  fixture:  {s.fixture.relative_to(ROOT)}")
            print(f"  expected: {s.expected.relative_to(ROOT)}")
            print(f"  out:      {s.out.relative_to(ROOT)}")
            print(f"  variants: {', '.join(list_variants(s))}")
        return 0

    if args.command == "clean":
        if args.scenario:
            if args.scenario not in by_name:
                print(f"Unknown scenario: {args.scenario}")
                return 2
            clean_scenario_outputs(by_name[args.scenario])
        else:
            for s in scenarios:
                clean_scenario_outputs(s)
        return 0

    if args.command == "run":
        scenario = by_name.get(args.scenario)
        if not scenario:
            print(f"Unknown scenario: {args.scenario}")
            return 2
        try:
            run_scenario(scenario, args.variant)
            return 0
        except subprocess.CalledProcessError as exc:
            print(f"FAIL  {scenario.name} [{args.variant}] (exit {exc.returncode})")
            return exc.returncode or 1
        except Exception as exc:
            print(f"FAIL  {scenario.name} [{args.variant}] - {exc}")
            return 1

    if args.command == "run-all":
        failures = 0
        for scenario in scenarios:
            variants = list_variants(scenario) if args.all_variants else ["base"]
            for variant in variants:
                try:
                    run_scenario(scenario, variant)
                except subprocess.CalledProcessError as exc:
                    failures += 1
                    print(f"FAIL  {scenario.name} [{variant}] (exit {exc.returncode})")
                except Exception as exc:
                    failures += 1
                    print(f"FAIL  {scenario.name} [{variant}] - {exc}")
        if failures:
            print(f"\nCompleted with {failures} failure(s).")
            return 1
        print("\nAll scenarios passed.")
        return 0

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
